<?php

namespace FooPlugins\FooPeople\Admin\Person;

use FooPlugins\FooPeople\Admin\Metaboxes\CustomPostTypeMetaboxFieldGroup;

if ( ! class_exists( 'FooPlugins\FooPeople\Admin\Person\MetaboxMainDetails' ) ) {

	class MetaboxMainDetails extends CustomPostTypeMetaboxFieldGroup {

		function __construct() {
			$field_group = apply_filters( 'FooPlugins\FooPeople\Admin\Person\MetaboxMainDetails\FieldGroup',
				array(
					'tabs' => array(
						array(
							'id'     => 'personal',
							'label'  => __( 'Personal', 'foopeople' ),
							'icon'   => 'dashicons-admin-users',
							'fields' => array(
								array(
									'id'       => 'firstname',
									'label'    => __( 'First Name', 'foopeople' ),
									'required' => true,
									'type'     => 'text',
									'default'  => '',
									'placeholder' => __( 'The first name of the person.', 'foopeople' ),
									'search_index' => true,
								),
								array(
									'id'       => 'surname',
									'label'    => __( 'Last Name', 'foopeople' ),
									'required' => true,
									'type'     => 'text',
									'default'  => '',
									'placeholder' => __( 'The last name/surname/family name of the person.', 'foopeople' ),
								),
								array(
									'id'       => 'preferred',
									'label'    => __( 'Preferred Name', 'foopeople' ),
									'desc'     => __( 'You can override the full name for the person. Leave blank to default the full name to be "First Name + Last Name".', 'foopeople' ),
									'required' => false,
									'type'     => 'text',
									'default'  => '',
									'placeholder' => __( 'This could be a nickname or a shortened name', 'foopeople' ),
								),
								array(
									'id'       => 'ethnicity',
									'label'    => __( 'Ethnicity', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'required' => false,
									'type'     => 'text',
									'default'  => ''
								),
								array(
									'id'       => 'gender',
									'required' => true,
									'label'    => __( 'Gender', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'type'     => 'radiolist',
									'choices' => array(
										'male' => __( 'Male', 'foopeople' ),
										'female' => __( 'Female', 'foopeople' ),
										'other' => __( 'Other', 'foopeople' ),
									)
								),
								array(
									'id'       => 'maritalstatus',
									'required' => true,
									'label'    => __( 'Marital Status', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'type'     => 'radiolist',
									'choices' => array(
										'single' => __( 'Single', 'foopeople' ),
										'married' => __( 'Married', 'foopeople' ),
										'divorced' => __( 'Divorced', 'foopeople' ),
										'widowed' => __( 'Widowed', 'foopeople' ),
									)
								),

								array(
									'id'       => 'postaladdress',
									'label'    => __( 'Postal Address', 'foopeople' ),
									'type'     => 'textarea',
								),
								array(
									'id'       => 'residentialaddress',
									'label'    => __( 'Residential Address', 'foopeople' ),
									'type'     => 'textarea',
								),
								array(
									'id'       => 'religion',
									'label'    => __( 'Religion', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'required' => false,
									'type'     => 'text',
								),
								array(
									'id'       => 'dob',
									'label'    => __( 'Date of Birth', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'required' => true,
									'type'     => 'date',
									'min'     => '1950-01-01',
									'max'     => date("Y-m-d"),
								),
								array(
									'id'       => 'idnumber',
									'label'    => __( 'ID Number / Social Security Number', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'type'     => 'text',
									'default'  => '',
								),
								array(
									'id'       => 'timezone',
									'label'    => __( 'Timezone', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'type'     => 'select',
									'choices' => array(
										'GMT'		=> __( 'GMT' , 'foopeople' ),
										'UTC-12'	=> __( 'UTC-12' , 'foopeople' ),
										'UTC-11.5'	=> __( 'UTC-11:30' , 'foopeople' ),
										'UTC-11'	=> __( 'UTC-11' , 'foopeople' ),
										'UTC-10.5'	=> __( 'UTC-10:30' , 'foopeople' ),
										'UTC-10'	=> __( 'UTC-10' , 'foopeople' ),
										'UTC-9.5'	=> __( 'UTC-9:30' , 'foopeople' ),
										'UTC-9'		=> __( 'UTC-9' , 'foopeople' ),
										'UTC-8.5'	=> __( 'UTC-8:30' , 'foopeople' ),
										'UTC-8'		=> __( 'UTC-8' , 'foopeople' ),
										'UTC-7.5'	=> __( 'UTC-7:30' , 'foopeople' ),
										'UTC-7'		=> __( 'UTC-7' , 'foopeople' ),
										'UTC-6.5'	=> __( 'UTC-6:30' , 'foopeople' ),
										'UTC-6'		=> __( 'UTC-6' , 'foopeople' ),
										'UTC-5.5'	=> __( 'UTC-5:30' , 'foopeople' ),
										'UTC-5'		=> __( 'UTC-5' , 'foopeople' ),
										'UTC-4.5'	=> __( 'UTC-4:30' , 'foopeople' ),
										'UTC-4'		=> __( 'UTC-4' , 'foopeople' ),
										'UTC-3.5'	=> __( 'UTC-3:30' , 'foopeople' ),
										'UTC-3'		=> __( 'UTC-3' , 'foopeople' ),
										'UTC-2.5'	=> __( 'UTC-2:30' , 'foopeople' ),
										'UTC-2'		=> __( 'UTC-2' , 'foopeople' ),
										'UTC-1.5'	=> __( 'UTC-1:30' , 'foopeople' ),
										'UTC-1'		=> __( 'UTC-1' , 'foopeople' ),
										'UTC-0.5'	=> __( 'UTC-0:30' , 'foopeople' ),
										'UTC+0'		=> __( 'UTC+0' , 'foopeople' ),
										'UTC+0.5'	=> __( 'UTC+0:30' , 'foopeople' ),
										'UTC+1'		=> __( 'UTC+1' , 'foopeople' ),
										'UTC+1.5'	=> __( 'UTC+1:30' , 'foopeople' ),
										'UTC+2'		=> __( 'UTC+2' , 'foopeople' ),
										'UTC+2.5'	=> __( 'UTC+2:30' , 'foopeople' ),
										'UTC+3'		=> __( 'UTC+3' , 'foopeople' ),
										'UTC+3.5'	=> __( 'UTC+3:30' , 'foopeople' ),
										'UTC+4'		=> __( 'UTC+4' , 'foopeople' ),
										'UTC+4.5'	=> __( 'UTC+4:30' , 'foopeople' ),
										'UTC+5'		=> __( 'UTC+5' , 'foopeople' ),
										'UTC+5.5'	=> __( 'UTC+5:30' , 'foopeople' ),
										'UTC+5.75'	=> __( 'UTC+5:45' , 'foopeople' ),
										'UTC+6'		=> __( 'UTC+6' , 'foopeople' ),
										'UTC+6.5'	=> __( 'UTC+6:30' , 'foopeople' ),
										'UTC+7'		=> __( 'UTC+7' , 'foopeople' ),
										'UTC+7.5'	=> __( 'UTC+7:30' , 'foopeople' ),
										'UTC+8'		=> __( 'UTC+8' , 'foopeople' ),
										'UTC+8.5'	=> __( 'UTC+8:30' , 'foopeople' ),
										'UTC+8.75'	=> __( 'UTC+8:45' , 'foopeople' ),
										'UTC+9'		=> __( 'UTC+9' , 'foopeople' ),
										'UTC+9.5'	=> __( 'UTC+9:30' , 'foopeople' ),
										'UTC+10'	=> __( 'UTC+10' , 'foopeople' ),
										'UTC+10.5'	=> __( 'UTC+10:30' , 'foopeople' ),
										'UTC+11'	=> __( 'UTC+11' , 'foopeople' ),
										'UTC+11.5'	=> __( 'UTC+11:30' , 'foopeople' ),
										'UTC+12'	=> __( 'UTC+12' , 'foopeople' ),
										'UTC+12.75'	=> __( 'UTC+12:45' , 'foopeople' ),
										'UTC+13'	=> __( 'UTC+13' , 'foopeople' ),
										'UTC+13.75'	=> __( 'UTC+13:45' , 'foopeople' ),
										'UTC+14'	=> __( 'UTC+14' , 'foopeople' ),
									)
								),
								array(
									'id'       => 'nationality',
									'label'    => __( 'Nationality', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'type'     => 'select',
									'choices' => array(
										'Afghanistan' => __( 'Afghanistan', 'foopeople' ),
										'Albania' => __( 'Albania', 'foopeople' ),
										'Algeria' => __( 'Algeria', 'foopeople' ),
										'Andorra' => __( 'Andorra', 'foopeople' ),
										'Angola' => __( 'Angola', 'foopeople' ),
										'Antigua & Deps' => __( 'Antigua & Deps', 'foopeople' ),
										'Argentina' => __( 'Argentina', 'foopeople' ),
										'Armenia' => __( 'Armenia', 'foopeople' ),
										'Australia' => __( 'Australia', 'foopeople' ),
										'Austria' => __( 'Austria', 'foopeople' ),
										'Azerbaijan' => __( 'Azerbaijan', 'foopeople' ),
										'Bahamas' => __( 'Bahamas', 'foopeople' ),
										'Bahrain' => __( 'Bahrain', 'foopeople' ),
										'Bangladesh' => __( 'Bangladesh', 'foopeople' ),
										'Barbados' => __( 'Barbados', 'foopeople' ),
										'Belarus' => __( 'Belarus', 'foopeople' ),
										'Belgium' => __( 'Belgium', 'foopeople' ),
										'Belize' => __( 'Belize', 'foopeople' ),
										'Benin' => __( 'Benin', 'foopeople' ),
										'Bhutan' => __( 'Bhutan', 'foopeople' ),
										'Bolivia' => __( 'Bolivia', 'foopeople' ),
										'Bosnia Herzegovina' => __( 'Bosnia Herzegovina', 'foopeople' ),
										'Botswana' => __( 'Botswana', 'foopeople' ),
										'Brazil' => __( 'Brazil', 'foopeople' ),
										'Brunei' => __( 'Brunei', 'foopeople' ),
										'Bulgaria' => __( 'Bulgaria', 'foopeople' ),
										'Burkina' => __( 'Burkina', 'foopeople' ),
										'Burundi' => __( 'Burundi', 'foopeople' ),
										'Cambodia' => __( 'Cambodia', 'foopeople' ),
										'Cameroon' => __( 'Cameroon', 'foopeople' ),
										'Canada' => __( 'Canada', 'foopeople' ),
										'Cape Verde' => __( 'Cape Verde', 'foopeople' ),
										'Central African Rep' => __( 'Central African Rep', 'foopeople' ),
										'Chad' => __( 'Chad', 'foopeople' ),
										'Chile' => __( 'Chile', 'foopeople' ),
										'China' => __( 'China', 'foopeople' ),
										'Colombia' => __( 'Colombia', 'foopeople' ),
										'Comoros' => __( 'Comoros', 'foopeople' ),
										'Congo' => __( 'Congo', 'foopeople' ),
										'Congo {Democratic Rep}' => __( 'Congo {Democratic Rep}', 'foopeople' ),
										'Costa Rica' => __( 'Costa Rica', 'foopeople' ),
										'Croatia' => __( 'Croatia', 'foopeople' ),
										'Cuba' => __( 'Cuba', 'foopeople' ),
										'Cyprus' => __( 'Cyprus', 'foopeople' ),
										'Czech Republic' => __( 'Czech Republic', 'foopeople' ),
										'Denmark' => __( 'Denmark', 'foopeople' ),
										'Djibouti' => __( 'Djibouti', 'foopeople' ),
										'Dominica' => __( 'Dominica', 'foopeople' ),
										'Dominican Republic' => __( 'Dominican Republic', 'foopeople' ),
										'East Timor' => __( 'East Timor', 'foopeople' ),
										'Ecuador' => __( 'Ecuador', 'foopeople' ),
										'Egypt' => __( 'Egypt', 'foopeople' ),
										'El Salvador' => __( 'El Salvador', 'foopeople' ),
										'Equatorial Guinea' => __( 'Equatorial Guinea', 'foopeople' ),
										'Eritrea' => __( 'Eritrea', 'foopeople' ),
										'Estonia' => __( 'Estonia', 'foopeople' ),
										'Ethiopia' => __( 'Ethiopia', 'foopeople' ),
										'Fiji' => __( 'Fiji', 'foopeople' ),
										'Finland' => __( 'Finland', 'foopeople' ),
										'France' => __( 'France', 'foopeople' ),
										'Gabon' => __( 'Gabon', 'foopeople' ),
										'Gambia' => __( 'Gambia', 'foopeople' ),
										'Georgia' => __( 'Georgia', 'foopeople' ),
										'Germany' => __( 'Germany', 'foopeople' ),
										'Ghana' => __( 'Ghana', 'foopeople' ),
										'Greece' => __( 'Greece', 'foopeople' ),
										'Grenada' => __( 'Grenada', 'foopeople' ),
										'Guatemala' => __( 'Guatemala', 'foopeople' ),
										'Guinea' => __( 'Guinea', 'foopeople' ),
										'Guinea-Bissau' => __( 'Guinea-Bissau', 'foopeople' ),
										'Guyana' => __( 'Guyana', 'foopeople' ),
										'Haiti' => __( 'Haiti', 'foopeople' ),
										'Honduras' => __( 'Honduras', 'foopeople' ),
										'Hungary' => __( 'Hungary', 'foopeople' ),
										'Iceland' => __( 'Iceland', 'foopeople' ),
										'India' => __( 'India', 'foopeople' ),
										'Indonesia' => __( 'Indonesia', 'foopeople' ),
										'Iran' => __( 'Iran', 'foopeople' ),
										'Iraq' => __( 'Iraq', 'foopeople' ),
										'Ireland {Republic}' => __( 'Ireland {Republic}', 'foopeople' ),
										'Israel' => __( 'Israel', 'foopeople' ),
										'Italy' => __( 'Italy', 'foopeople' ),
										'Ivory Coast' => __( 'Ivory Coast', 'foopeople' ),
										'Jamaica' => __( 'Jamaica', 'foopeople' ),
										'Japan' => __( 'Japan', 'foopeople' ),
										'Jordan' => __( 'Jordan', 'foopeople' ),
										'Kazakhstan' => __( 'Kazakhstan', 'foopeople' ),
										'Kenya' => __( 'Kenya', 'foopeople' ),
										'Kiribati' => __( 'Kiribati', 'foopeople' ),
										'Korea North' => __( 'Korea North', 'foopeople' ),
										'Korea South' => __( 'Korea South', 'foopeople' ),
										'Kosovo' => __( 'Kosovo', 'foopeople' ),
										'Kuwait' => __( 'Kuwait', 'foopeople' ),
										'Kyrgyzstan' => __( 'Kyrgyzstan', 'foopeople' ),
										'Laos' => __( 'Laos', 'foopeople' ),
										'Latvia' => __( 'Latvia', 'foopeople' ),
										'Lebanon' => __( 'Lebanon', 'foopeople' ),
										'Lesotho' => __( 'Lesotho', 'foopeople' ),
										'Liberia' => __( 'Liberia', 'foopeople' ),
										'Libya' => __( 'Libya', 'foopeople' ),
										'Liechtenstein' => __( 'Liechtenstein', 'foopeople' ),
										'Lithuania' => __( 'Lithuania', 'foopeople' ),
										'Luxembourg' => __( 'Luxembourg', 'foopeople' ),
										'Macedonia' => __( 'Macedonia', 'foopeople' ),
										'Madagascar' => __( 'Madagascar', 'foopeople' ),
										'Malawi' => __( 'Malawi', 'foopeople' ),
										'Malaysia' => __( 'Malaysia', 'foopeople' ),
										'Maldives' => __( 'Maldives', 'foopeople' ),
										'Mali' => __( 'Mali', 'foopeople' ),
										'Malta' => __( 'Malta', 'foopeople' ),
										'Marshall Islands' => __( 'Marshall Islands', 'foopeople' ),
										'Mauritania' => __( 'Mauritania', 'foopeople' ),
										'Mauritius' => __( 'Mauritius', 'foopeople' ),
										'Mexico' => __( 'Mexico', 'foopeople' ),
										'Micronesia' => __( 'Micronesia', 'foopeople' ),
										'Moldova' => __( 'Moldova', 'foopeople' ),
										'Monaco' => __( 'Monaco', 'foopeople' ),
										'Mongolia' => __( 'Mongolia', 'foopeople' ),
										'Montenegro' => __( 'Montenegro', 'foopeople' ),
										'Morocco' => __( 'Morocco', 'foopeople' ),
										'Mozambique' => __( 'Mozambique', 'foopeople' ),
										'Myanmar, {Burma}' => __( 'Myanmar, {Burma}', 'foopeople' ),
										'Namibia' => __( 'Namibia', 'foopeople' ),
										'Nauru' => __( 'Nauru', 'foopeople' ),
										'Nepal' => __( 'Nepal', 'foopeople' ),
										'Netherlands' => __( 'Netherlands', 'foopeople' ),
										'New Zealand' => __( 'New Zealand', 'foopeople' ),
										'Nicaragua' => __( 'Nicaragua', 'foopeople' ),
										'Niger' => __( 'Niger', 'foopeople' ),
										'Nigeria' => __( 'Nigeria', 'foopeople' ),
										'Norway' => __( 'Norway', 'foopeople' ),
										'Oman' => __( 'Oman', 'foopeople' ),
										'Pakistan' => __( 'Pakistan', 'foopeople' ),
										'Palau' => __( 'Palau', 'foopeople' ),
										'Panama' => __( 'Panama', 'foopeople' ),
										'Papua New Guinea' => __( 'Papua New Guinea', 'foopeople' ),
										'Paraguay' => __( 'Paraguay', 'foopeople' ),
										'Peru' => __( 'Peru', 'foopeople' ),
										'Philippines' => __( 'Philippines', 'foopeople' ),
										'Poland' => __( 'Poland', 'foopeople' ),
										'Portugal' => __( 'Portugal', 'foopeople' ),
										'Qatar' => __( 'Qatar', 'foopeople' ),
										'Romania' => __( 'Romania', 'foopeople' ),
										'Russian Federation' => __( 'Russian Federation', 'foopeople' ),
										'Rwanda' => __( 'Rwanda', 'foopeople' ),
										'St Kitts & Nevis' => __( 'St Kitts & Nevis', 'foopeople' ),
										'St Lucia' => __( 'St Lucia', 'foopeople' ),
										'Saint Vincent & the Grenadines' => __( 'Saint Vincent & the Grenadines', 'foopeople' ),
										'Samoa' => __( 'Samoa', 'foopeople' ),
										'San Marino' => __( 'San Marino', 'foopeople' ),
										'Sao Tome & Principe' => __( 'Sao Tome & Principe', 'foopeople' ),
										'Saudi Arabia' => __( 'Saudi Arabia', 'foopeople' ),
										'Senegal' => __( 'Senegal', 'foopeople' ),
										'Serbia' => __( 'Serbia', 'foopeople' ),
										'Seychelles' => __( 'Seychelles', 'foopeople' ),
										'Sierra Leone' => __( 'Sierra Leone', 'foopeople' ),
										'Singapore' => __( 'Singapore', 'foopeople' ),
										'Slovakia' => __( 'Slovakia', 'foopeople' ),
										'Slovenia' => __( 'Slovenia', 'foopeople' ),
										'Solomon Islands' => __( 'Solomon Islands', 'foopeople' ),
										'Somalia' => __( 'Somalia', 'foopeople' ),
										'South Africa' => __( 'South Africa', 'foopeople' ),
										'South Sudan' => __( 'South Sudan', 'foopeople' ),
										'Spain' => __( 'Spain', 'foopeople' ),
										'Sri Lanka' => __( 'Sri Lanka', 'foopeople' ),
										'Sudan' => __( 'Sudan', 'foopeople' ),
										'Suriname' => __( 'Suriname', 'foopeople' ),
										'Swaziland' => __( 'Swaziland', 'foopeople' ),
										'Sweden' => __( 'Sweden', 'foopeople' ),
										'Switzerland' => __( 'Switzerland', 'foopeople' ),
										'Syria' => __( 'Syria', 'foopeople' ),
										'Taiwan' => __( 'Taiwan', 'foopeople' ),
										'Tajikistan' => __( 'Tajikistan', 'foopeople' ),
										'Tanzania' => __( 'Tanzania', 'foopeople' ),
										'Thailand' => __( 'Thailand', 'foopeople' ),
										'Togo' => __( 'Togo', 'foopeople' ),
										'Tonga' => __( 'Tonga', 'foopeople' ),
										'Trinidad & Tobago' => __( 'Trinidad & Tobago', 'foopeople' ),
										'Tunisia' => __( 'Tunisia', 'foopeople' ),
										'Turkey' => __( 'Turkey', 'foopeople' ),
										'Turkmenistan' => __( 'Turkmenistan', 'foopeople' ),
										'Tuvalu' => __( 'Tuvalu', 'foopeople' ),
										'Uganda' => __( 'Uganda', 'foopeople' ),
										'Ukraine' => __( 'Ukraine', 'foopeople' ),
										'United Arab Emirates' => __( 'United Arab Emirates', 'foopeople' ),
										'United Kingdom' => __( 'United Kingdom', 'foopeople' ),
										'United States' => __( 'United States', 'foopeople' ),
										'Uruguay' => __( 'Uruguay', 'foopeople' ),
										'Uzbekistan' => __( 'Uzbekistan', 'foopeople' ),
										'Vanuatu' => __( 'Vanuatu', 'foopeople' ),
										'Vatican City' => __( 'Vatican City', 'foopeople' ),
										'Venezuela' => __( 'Venezuela', 'foopeople' ),
										'Vietnam' => __( 'Vietnam', 'foopeople' ),
										'Yemen' => __( 'Yemen', 'foopeople' ),
										'Zambia' => __( 'Zambia', 'foopeople' ),
										'Zimbabwe' => __( 'Zimbabwe', 'foopeople' ),
									)
								)
							)
						),
						array(
							'id'     => 'professional',
							'label'  => __( 'Professional', 'foopeople' ),
							'icon'   => 'dashicons-businesswoman',
							'fields' => array(
								array(
									'id'       => 'workemail',
									'label'    => __( 'Email', 'foopeople' ),
									'required' => true,
									'type'     => 'text',
								),
								array(
									'id'       => 'employeenumber',
									'label'    => __( 'Employee Number', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'type'     => 'text',
									'default'  => '',
								),
								array(
									'id'       => 'employmenttype',
									'label'    => __( 'Employment Type', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'type'     => 'select',
									'choices' => array(
										'fulltime' => __( 'Fulltime', 'foopeople' ),
										'parttime' => __( 'Part Time', 'foopeople' ),
										'contractor' => __( 'Contractor', 'foopeople' ),
										'temporary' => __( 'Temporary', 'foopeople' ),
										'trainee' => __( 'Trainee', 'foopeople' ),
										'intern' => __( 'Intern', 'foopeople' ),

									)
								),
								array(
									'id'       => 'datejoined',
									'label'    => __( 'Date Joined', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'required' => true,
									'type'     => 'date',
									'min'     => '1950-01-01',
									'max'     => date("Y-m-d"),
									'default'  => '',
									'placeholder' => __( '', 'foopeople' )
								),
								array(
									'id'       => 'salary',
									'label'    => __( 'Salary', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'type'     => 'number',
									'default'  => '',
								),
								array(
									'id'       => 'jobtitle',
									'label'    => __( 'Job Title', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'required' => true,
									'type'     => 'text',
									'default'  => '',
									'placeholder' => __( 'Job title', 'foopeople' ),
								),
								array(
									'id'       => 'manager',
									'label'    => __( 'Line Manager', 'foopeople' ),
									'desc'     => __( '', 'foopeople' ),
									'type'     => 'selectize',
									'default'  => '',
									'placeholder' => __( 'Start typing the manager name', 'foopeople' ),
									'query_type' => 'post',
									'query_data' => FOOPEOPLE_CPT_PERSON
								),
							)
						),
						array(
							'id'     => 'portrait',
							'label'  => __( 'Portrait', 'foopeople' ),
							'icon'   => 'dashicons-format-image',
							'fields' => array(),
							'type'   => 'featured_image',
							'featuredImage' => true
						),
						array(
							'id'     => 'contactwork',
							'label'  => __( 'Work Contact', 'foopeople' ),
							'icon'   => 'dashicons-phone',
							'fields' => array(
								array(
									'id'       => 'workmobile',
									'label'    => __( 'Mobile Number', 'foopeople' ),
									'type'     => 'text',
								),
								array(
									'id'       => 'worklandline',
									'label'    => __( 'Landline', 'foopeople' ),
									'type'     => 'text',
								),
								array(
									'id'       => 'workslack',
									'label'    => __( 'Slack', 'foopeople' ),
									'type'     => 'text',
									'placeholder'  => 'name.slack.com',
								),
								array(
									'id'       => 'workteams',
									'label'    => __( 'Teams', 'foopeople' ),
									'type'     => 'text',
									'placeholder'  => 'teams.microsoft.com/name',
								),
								array(
									'id'       => 'workskype',
									'label'    => __( 'Skype', 'foopeople' ),
									'type'     => 'text',
									'placeholder'  => '@name',
								),
								array(
									'id'       => 'worktwitter',
									'label'    => __( 'Twitter', 'foopeople' ),
									'type'     => 'text',
									'placeholder'  => '@name',
								),
								array(
									'id'       => 'workfacebook',
									'label'    => __( 'Facebook', 'foopeople' ),
									'type'     => 'text',
									'placeholder'  => 'facebook.com/name',
								),
							)
						),
						array(
							'id'     => 'contactpersonal',
							'label'  => __( 'Personal Contact', 'foopeople' ),
							'icon'   => 'dashicons-phone',
							'fields' => array(
								array(
									'id'       => 'personalemail',
									'label'    => __( 'Email', 'foopeople' ),
									'type'     => 'text',
								),
								array(
									'id'       => 'personalphonenumber',
									'label'    => __( 'Phone Number', 'foopeople' ),
									'type'     => 'text',
								),
								array(
									'id'       => 'personalslack',
									'label'    => __( 'Slack', 'foopeople' ),
									'type'     => 'text',
									'placeholder'  => 'name.slack.com',
								),
								array(
									'id'       => 'personalteams',
									'label'    => __( 'Teams', 'foopeople' ),
									'type'     => 'text',
									'placeholder'  => 'teams.microsoft.com/name',
								),
								array(
									'id'       => 'personalskype',
									'label'    => __( 'Skype', 'foopeople' ),
									'type'     => 'text',
									'placeholder'  => '@name',
								),
								array(
									'id'       => 'personaltwitter',
									'label'    => __( 'Twitter', 'foopeople' ),
									'type'     => 'text',
									'placeholder'  => '@name',
								),
								array(
									'id'       => 'personalfacebook',
									'label'    => __( 'Facebook', 'foopeople' ),
									'type'     => 'text',
									'placeholder'  => 'facebook.com/name',
								),
								array(
									'id'       => 'personallinkedin',
									'label'    => __( 'LinkedIn', 'foopeople' ),
									'type'     => 'text',
									'placeholder'  => 'linkedin.com/in/name',
								),
							)
						),
						array(
							'id'     => 'medical',
							'label'  => __( 'Medical', 'foopeople' ),
							'icon'   => 'dashicons-plus',
							'fields' => array(
								array(
									'id'       => 'nextofkin',
									'label'    => __( 'Next of Kins details (name, contact details)', 'foopeople' ),
									'type'     => 'textarea',
								),
								array(
									'id'       => 'doctordetails',
									'label'    => __( 'Doctors details (name, contact details)', 'foopeople' ),
									'type'     => 'textarea',
								),
								array(
									'id'       => 'bloodtype',
									'label'    => __( 'Blood Type', 'foopeople' ),
									'type'     => 'select',
									'choices' => array(
										'A+' => __( 'A+', 'foopeople' ),
										'A-' => __( 'A-', 'foopeople' ),
										'B+' => __( 'B+', 'foopeople' ),
										'B-' => __( 'B-', 'foopeople' ),
										'O+' => __( 'O+', 'foopeople' ),
										'O-' => __( 'O-', 'foopeople' ),
										'AB+' => __( 'AB+', 'foopeople' ),
										'AB-' => __( 'AB-', 'foopeople' ),
									)
								),
								array(
									'id'       => 'allergies',
									'label'    => __( 'Allergies', 'foopeople' ),
									'type'     => 'textarea',
								),
							)
						),
						array(
							'id'     => 'teams',
							'label'  => __( 'Teams', 'foopeople' ),
							'icon'   => 'dashicons-groups',
							'type'   => 'taxonomy',
							'fields' => array(),
							'taxonomy' => FOOPEOPLE_CT_TEAM
						),
						array(
							'id'     => 'skills',
							'label'  => __( 'Skills', 'foopeople' ),
							'icon'   => 'dashicons-tag',
							'type'   => 'taxonomy',
							'fields' => array(),
							'taxonomy' => FOOPEOPLE_CT_SKILL
						),
						array(
							'id'     => 'locations',
							'label'  => __( 'Locations', 'foopeople' ),
							'icon'   => 'dashicons-admin-site',
							'type'   => 'taxonomy',
							'fields' => array(),
							'taxonomy' => FOOPEOPLE_CT_LOCATION
						),
					)
				) );

			parent::__construct(
				array(
					'post_type'      => FOOPEOPLE_CPT_PERSON,
					'metabox_id'     => 'details',
					'metabox_title'  => __( 'Main Details', 'pacepeople' ),
					'priority'       => 'high',
					'meta_key'       => FOOPEOPLE_META_PERSON_MAIN,
					'plugin_url'     => FOOPEOPLE_URL,
					'plugin_version' => FOOPEOPLE_VERSION
				),
				$field_group
			);
		}
	}
}
